services:
  - type: web
    name: stress-detection
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app1:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13